// Do not modify. Generated by ./build.sh
var GENERATED = {}
GENERATED.themes = [
"_CST_ tomorrow-theme",
"_CST_ tomorrow-theme-night",
"_CST_ tomorrow-theme-night-blue",
"_CST_ tomorrow-theme-night-bright",
"_CST_ tomorrow-theme-night-eighties",
"" // original native theme
];
